<?php
// START MEMANGGIL FILE CONFIG UNTUK MENGHUBUNGKAN KE DATABASE SERVER
require_once ("config.php");
// FINISH MEMANGGIL FILE CONFIG UNTUK MENGHUBUNGKAN KE DATABASE SERVER

// START DEKLARASI VARIABEL INPUT PADA HALAMAN SEBELUMNYA GET METHOD
$id_barang = mysqli_real_escape_string($link,strip_tags($_GET['id_barang']));
// FINISH DEKLARASI VARIABEL INPUT PADA HALAMAN SEBELUMNYA GET METHOD

// START DEKLARASI VARIABEL ID USER DENGAN MEMANGGIL ID YANG LOGIN PADA SESSION
$id_user = $_SESSION['user_login'];
// FINISH DEKLARASI VARIABEL ID USER DENGAN MEMANGGIL ID YANG LOGIN PADA SESSION

// START CEK DATA BARANG DI DATABASE BERDASARKAN ID BARANG
$data_barang = mysqli_fetch_assoc(mysqli_query($link,"SELECT * FROM barang WHERE id_barang='$id_barang' "));
// FINISH CEK DATA BARANG DI DATABASE BERDASARKAN ID BARANG

// START PROSES PENGHAPUSAN DATA BARANG DI TABEL CART DI DATABASE
mysqli_query($link, "DELETE FROM cart WHERE id_barang='$id_barang' AND id_user='$id_user' ");
// FINISH PROSES PENGHAPUSAN DATA BARANG DI TABEL CART DI DATABASE

// START PROSES REDIRECT KE HALAMAN CART & TAMPILKAN ALERT SUKSES JIKA PROSES PENGHAPUSAN DATA BARANG SELESAI
    header("location:cart.php?status=sukses&keterangan=DATA BARANG - ". $data_barang['nama_barang'] ." BERHASIL DI HAPUS DARI CART !");
// FINISH PROSES REDIRECT KE HALAMAN CART & TAMPILKAN ALERT SUKSES JIKA PROSES PENGHAPUSAN DATA BARANG SELESAI
?>