<?php
// START MEMANGGIL FILE CONFIG UNTUK MENGHUBUNGKAN KE DATABASE SERVER
require_once ("../config.php");
// FINISH MEMANGGIL FILE CONFIG UNTUK MENGHUBUNGKAN KE DATABASE SERVER

// PANGGIL FILE CEK STATUS LOGIN
include "cek_status_login_admin.php";

// START DEKLARASI VARIABEL INPUT PADA HALAMAN SEBELUMNYA GET METHOD
$id_barang = mysqli_real_escape_string($link,strip_tags($_GET['id_barang']));
// FINISH DEKLARASI VARIABEL INPUT PADA HALAMAN SEBELUMNYA GET METHOD

// START CEK DATA BARANG DI DATABASE BERDASARKAN ID BARANG
$data_barang = mysqli_fetch_assoc(mysqli_query($link,"SELECT * FROM barang WHERE id_barang='$id_barang' "));
// FINISH CEK DATA BARANG DI DATABASE BERDASARKAN ID BARANG


// START PROSES PENGHAPUSAN FOTO/GAMBAR BARANG DI DIREKTORI SERVER
unlink("../asset/gambar_barang/".$data_barang['foto_barang']."png");
// FINISH PROSES PENGHAPUSAN FOTO/GAMBAR BARANG DI DIREKTORI SERVER

// START PROSES PENGHAPUSAN DATA BARANG DI DATABASE
mysqli_query($link, "DELETE FROM barang WHERE id_barang='$id_barang' ");
// FINISH PROSES PENGHAPUSAN DATA BARANG DI DATABASE

// START PROSES REDIRECT KE HALAMAN DAFTAR BARANG & TAMPILKAN ALERT SUKSES JIKA PROSES PENGHAPUSAN DATA BARANG SELESAI
    header("location:daftar_barang.php?status=sukses&keterangan=DATA BARANG - ". $data_barang['nama_barang'] ." BERHASIL DI HAPUS !");
// FINISH PROSES REDIRECT KE HALAMAN DAFTAR BARANG & TAMPILKAN ALERT SUKSES JIKA PROSES PENGHAPUSAN DATA BARANG SELESAI
?>